# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Ghostfolio installation tasks
  when: ghostfolio_enabled | bool
  tags:
    - setup-all
    - setup-ghostfolio
    - install-all
    - install-ghostfolio
  block:
    - name: Validate Ghostfolio configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Ghostfolio
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Ghostfolio uninstallation tasks
  when: not ghostfolio_enabled | bool
  tags:
    - setup-all
    - setup-ghostfolio
  block:
    - name: Uninstall Ghostfolio
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
