# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Ghostfolio installation tasks
  block:
    - name: Validate Ghostfolio configuration
      when: ghostfolio_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Ghostfolio
      when: ghostfolio_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-ghostfolio
    - install-all
    - install-ghostfolio

- name: Perform Ghostfolio uninstallation tasks
  block:
    - name: Uninstall Ghostfolio
      when: not ghostfolio_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-ghostfolio
