# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required Ghostfolio settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - docmost_uid
    - docmost_gid
    - docmost_hostname
    - docmost_path_prefix
    - docmost_container_network
    - docmost_environment_variable_redis_url

- when: docmost_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Ghostfolio Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - docmost_container_labels_traefik_hostname
        - docmost_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `docmost_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if docmost_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          docmost_container_labels_traefik_path_prefix (`{{ docmost_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/docmost`).
      when: "docmost_container_labels_traefik_path_prefix != '/' and docmost_container_labels_traefik_path_prefix[-1] == '/'"
