# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "ghostfolio_database_host", "new": "ghostfolio_database_hostname" }
    - { "old": "ghostfolio_redis_host", "new": "ghostfolio_redis_hostname" }
    - { "old": "ghostfolio_environment_variable_redis_port", "new": "ghostfolio_redis_port" }
    - { "old": "ghostfolio_environment_variable_redis_password", "new": "ghostfolio_redis_password" }
    - { "old": "ghostfolio_environment_variable_redis_db", "new": "ghostfolio_redis_db" }

- name: Fail if required Ghostfolio settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - ghostfolio_uid
    - ghostfolio_gid
    - ghostfolio_hostname
    - ghostfolio_path_prefix
    - ghostfolio_container_network

- name: Fail if Ghostfolio logging level is invalid
  ansible.builtin.fail:
    msg: >-
      ghostfolio_environment_variable_log_levels must be 'debug', 'error', 'log', or 'warn'
  when: "ghostfolio_environment_variable_log_levels not in ['debug', 'error', 'log', 'warn']"

- name: Run if Traefik is enabled
  when: ghostfolio_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Ghostfolio are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - ghostfolio_container_labels_traefik_hostname
        - ghostfolio_container_labels_traefik_path_prefix

    - name: Fail if ghostfolio_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          ghostfolio_container_labels_traefik_path_prefix (`{{ ghostfolio_container_labels_traefik_path_prefix }}`) must be `/`.
          Ghostfolio does not support hosting under a subpath yet.
      when: "ghostfolio_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `ghostfolio_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if ghostfolio_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          ghostfolio_container_labels_traefik_path_prefix (`{{ ghostfolio_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/ghostfolio`).
      when: "ghostfolio_container_labels_traefik_path_prefix != '/' and ghostfolio_container_labels_traefik_path_prefix[-1] == '/'"
